FROM php:8.2.4-cli-alpine

RUN set -ex \
    && apk --no-cache add \
    postgresql-dev libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql